### ISSUE TITLE
Missing name property in HTTPError class

### ISSUE THREAD

**Issue by Garrett1Tolbert** [kodewilliams/scaffold#4]
Missing `name` property in the `HTTPError` class. Simple fix, I just thought I'd point it out.

https://github.com/kodewilliams/scaffold/blob/7e95dd69593040f5e215592205e0a94b54f2b9c4/serverless/gcp/src/global/errors.ts#L3-L11

**Comment by kodewilliams** [comment]
`name` exists on the Error base class being extended, no need for it here.
